export enum API_KEYS {
  DESIGNATIONS = "DESIGNATIONS",
  DEPARTMENTS = "DEPARTMENTS",
  DASHBOARD = "DASHBOARD",
  USER = "USER",
  USERS = "USERS",
  TEAMS = "TEAMS",
  TEAM = "TEAM",
  ROLES = "ROLES",
  ME = "ME",
}
